[package]
name = "spin"
version = "0.1.0"
authors = ["rookie1024 <rookie1286@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.16.1"

[dependencies]
clap = "2.32.0"
lalrpop-util = "0.16.1"
regex = "1.0.5"
